// UI Control
export const OPEN_SIDER = "OPEN_SIDER";
export const CLOSE_SIDER = "CLOSE_SIDER";
export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";

// Auth
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

// User
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

// Debate
export const GET_DEBATES_REQUEST = "GET_DEBATES_REQUEST";
export const GET_DEBATES_SUCCESS = "GET_DEBATES_SUCCESS";
export const GET_DEBATES_FAILURE = "GET_DEBATES_FAILURE";
export const DELETE_DEBATES_REQUEST = "DELETE_DEBATES_REQUEST";
export const DELETE_DEBATES_SUCCESS = "DELETE_DEBATES_SUCCESS";
export const DELETE_DEBATES_FAILURE = "DELETE_DEBATES_FAILURE";

// QnA
export const GET_QNAS_REQUEST = "GET_QNAS_REQUEST";
export const GET_QNAS_SUCCESS = "GET_QNAS_SUCCESS";
export const GET_QNAS_FAILURE = "GET_QNAS_FAILURE";
export const GET_QNA_DETAIL_REQUEST = "GET_QNA_DETAIL_REQUEST";
export const GET_QNA_DETAIL_SUCCESS = "GET_QNA_DETAIL_SUCCESS";
export const GET_QNA_DETAIL_FAILURE = "GET_QNA_DETAIL_FAILURE";
export const UPDATE_QNA_COMMENT_REQUEST = "UPDATE_QNA_COMMENT_REQUEST";
export const UPDATE_QNA_COMMENT_SUCCESS = "UPDATE_QNA_COMMENT_SUCCESS";
export const UPDATE_QNA_COMMENT_FAILURE = "UPDATE_QNA_COMMENT_FAILURE";
export const DELETE_QNA_COMMENT_REQUEST = "DELETE_QNA_COMMENT_REQUEST";
export const DELETE_QNA_COMMENT_SUCCESS = "DELETE_QNA_COMMENT_SUCCESS";
export const DELETE_QNA_COMMENT_FAILURE = "DELETE_QNA_COMMENT_FAILURE";

// Page
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

// Statistic
export const GET_DAILY_STATISTIC_REQUEST = "GET_DAILY_STATISTIC_REQUEST";
export const GET_DAILY_STATISTIC_SUCCESS = "GET_DAILY_STATISTIC_SUCCESS";
export const GET_DAILY_STATISTIC_FAILURE = "GET_DAILY_STATISTIC_FAILURE";
